In [5]:
import numpy as np

In [16]:
np.__version__

'1.26.4'

In [13]:
import sys 
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 08:28:27) [Clang 14.0.6 ]'

# CREATING LIST 

In [18]:
my_list=[1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [21]:
type(my_list)

list

In [23]:
!pip install numpy

In [25]:
arr=np.array(my_list)

In [27]:
arr

array([1, 2, 3, 4, 5])

In [29]:
type(arr)

numpy.ndarray

In [31]:
type(my_list)

list

In [39]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [41]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [45]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [47]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [49]:
np.arange(20,10)   #1st argument > 2nd argument - we will get empty array

array([], dtype=int64)

In [51]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [53]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [57]:
ar=np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [59]:
np.arange(10,30,5)  ## STEP INDEX WITH 5 VALUES GAP # in arange we can do upto 3 parameters only

array([10, 15, 20, 25])

In [61]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [63]:
np.zeros(10)  # parameter tuning -system use its own parameter by default as float

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# hyper parameter tuning  - system which he give

In [65]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [67]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

# 2d array

In [74]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [76]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [78]:
np.zeros((10,30),dtype=int)        # 10 rows & 30 columns

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [80]:
np.zeros((10,10)) # 10D array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [82]:
np.ones(3)

array([1., 1., 1.])

In [88]:
rand(3,2)

NameError: name 'rand' is not defined

In [90]:
random.rand(2,3)

NameError: name 'random' is not defined

In [92]:
np.random.rand(5)

array([0.52768681, 0.06253004, 0.25179659, 0.85814828, 0.23572684])

In [94]:
np.random.rand(6)

array([0.99030763, 0.36814643, 0.81153395, 0.81797928, 0.50776153,
       0.85675664])

In [96]:
np.random.rand(5)

array([0.35569417, 0.74279477, 0.94355623, 0.8171134 , 0.75368591])

In [98]:
np.random.rand(3,5)   ## with 3 rows and 5 columns 

array([[0.0106976 , 0.34820449, 0.44110705, 0.24701   , 0.23104161],
       [0.84940873, 0.47465981, 0.84725156, 0.67955458, 0.42536785],
       [0.29829377, 0.67767446, 0.50422442, 0.49690507, 0.47876892]])

In [104]:
np.random.randint(4,6)   ## we will get 4 or 5 but not 6 as high is exclusive

4

In [108]:
np.random.randint(2,20)   # by default we may get any value upto 20 everytime we execute but not 20

19

In [110]:
np.random.randint(2,20,5)  # between 2 to 20 randomly 5 numbers we will get - everytime we execute diff numbers we will get as OTP

array([16, 13,  2,  7, 17])

In [114]:
np.random.randint(10,40,(10,10))   ## 10-40 with 10 rows and 10 columns 

array([[19, 39, 32, 10, 22, 31, 34, 26, 11, 37],
       [23, 15, 12, 36, 13, 31, 37, 17, 15, 37],
       [14, 29, 31, 29, 38, 30, 11, 23, 32, 13],
       [34, 24, 10, 15, 15, 32, 18, 39, 30, 19],
       [18, 38, 34, 27, 34, 37, 11, 21, 37, 27],
       [15, 29, 34, 21, 39, 34, 39, 12, 37, 19],
       [19, 30, 39, 38, 23, 11, 12, 39, 38, 28],
       [33, 38, 20, 16, 33, 11, 34, 16, 20, 34],
       [19, 29, 29, 28, 19, 31, 31, 24, 29, 27],
       [24, 16, 37, 39, 33, 18, 32, 18, 30, 22]])

In [116]:
np.random.randint(10,40,(10,5))

array([[28, 17, 21, 24, 14],
       [11, 20, 12, 28, 34],
       [34, 16, 16, 18, 12],
       [35, 32, 38, 12, 20],
       [31, 24, 33, 14, 16],
       [27, 26, 32, 21, 17],
       [25, 26, 34, 15, 33],
       [29, 37, 25, 37, 10],
       [19, 35, 38, 30, 32],
       [20, 31, 26, 29, 36]])

In [118]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [120]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [122]:
np.arange(1,13).reshape(3,5)  # 3*5 =15 error as its invalid beacuse we have only 12 elemets

ValueError: cannot reshape array of size 12 into shape (3,5)

# slicing in matrix

In [129]:
b=np.random.randint(10,20,(5,4))

In [131]:
b

array([[17, 10, 17, 16],
       [18, 17, 13, 14],
       [17, 13, 15, 17],
       [15, 13, 17, 12],
       [18, 10, 17, 13]])

In [133]:
type(b)

numpy.ndarray

In [143]:
np.arange(1,19).reshape(3,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])